_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/ec/arcbin/arc_mikel2.py
        m:
            - "1": test-hit3
              "5": 2
              "6":
                - 1
                - 3
              "7":
                - 2
              "8": 2
            - "1": iteration
              "6":
                - 3
              "7": []
            - "1": batch
              "6":
                - 3
              "7": []
            - "1": recog-loss
              "5": 3
              "6":
                - 1
                - 3
              "7":
                - 1
              "8": 1
            - "1": recog-mdl
              "5": 3
              "6":
                - 1
                - 3
              "7":
                - 1
              "8": 1
            - "1": recog-class-loss
              "5": 3
              "6":
                - 1
                - 3
              "7":
                - 1
              "8": 1
            - "1": test-hit1
              "5": 2
              "6":
                - 1
                - 3
              "7":
                - 2
              "8": 2
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 7
                - 16
                - 23
                - 55
                - 63
                - 64
            "4": 3.11.2
            "5": 0.19.11
            "8":
                - 5
            "10":
                - 18
            "12": 0.19.11
            "13": linux-x86_64
CPUs:
    value: 4
activation:
    value: relu
addFullTaskMetrics:
    value: false
aic:
    value: 0.1
arity:
    value: 3
auxiliaryLoss:
    value: false
biasOptimal:
    value: false
bothset:
    value: false
compressor:
    value: ocaml
contextual:
    value: false
cuda:
    value: false
ensembleSize:
    value: 1
enumerationTimeout:
    value: 600
evalset:
    value: false
featureExtractor:
    value: dreamcoder.domains.arc.main.MikelArcNet
helmholtzRatio:
    value: 1
hostname:
    value: arc-dev2
iterations:
    value: 1
mask:
    value: false
matrixRank:
    value: null
maximumFrontier:
    value: 10
noConsolidation:
    value: false
pseudoCounts:
    value: 30
recognitionSteps:
    value: null
recognitionTimeout:
    value: 0
resume:
    value: null
reuseRecognition:
    value: false
rewriteTaskMetrics:
    value: false
seed:
    value: 0
solver:
    value: python
storeTaskMetrics:
    value: true
structurePenalty:
    value: 0.1
task_isolation:
    value: false
taskBatchSize:
    value: null
taskReranker:
    value: default
testEvery:
    value: 1
testingTimeout:
    value: 0
topK:
    value: 5
useDSL:
    value: true
useRecognitionModel:
    value: true
